version: '3'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    # networks:
    #   - webnet
    depends_on:
    - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - /home/cristian/.mongo-data/my-animes-list-back:/data/db
    command: --quiet
